#!/bin/bash

function fix_ssh {
  # check if ssh-eval has been ran

  matches=$(ps ax | grep -v "grep" | grep "ssh-agent" | awk '{print $1}')

  size=$(echo "$matches" | wc -l)

  if [[ $size -gt 0 && -n "${matches}" ]]; then
  
    i=1
    for p in $matches
    do

      if [[ $i -eq $size ]]; then
        echo "Using existing agent." 

        SSH_AGENT_PID=$p
        export SSH_AGENT_PID="$SSH_AGENT_PID"
        echo "$SSH_AGENT_PID"

        SSH_AUTH_SOCK="$HOME/.ssh/sock/.ssh-agent"
        echo "$SSH_AUTH_SOCK"
        export SSH_AUTH_SOCK="$SSH_AUTH_SOCK"

      else

        kill "$p"
        i=$((i+1))

      fi

    done

  else

    echo "Creating new agent."
    eval "$(ssh-agent -a "$HOME"/.ssh/sock/.ssh-agent)"

  fi
}

fix_ssh