#!/bin/bash

set -e

TIMESTAMP="$(date +"%Y%m%d%I%M%p")"
FILE="$HOME/notes/z/$TIMESTAMP.md"

mkdir -p "$(dirname "$FILE")"
printf '# %s\n##  \n' "$TIMESTAMP" >> "$FILE"

vim "+call cursor(2,4)" "$FILE"

if [ "$(wc -l < "$FILE")" -lt 3 ]; then
  rm "$FILE"
else
  TITLE=$(sed -n '2p' "$FILE" | sed -e 's/^## //' -e 's/ *$//')
  # -C keeps us out of pushd/popd, which broke on paths containing spaces.
  git -C "$HOME/notes" add "$FILE"
  git -C "$HOME/notes" commit -m "Add new zet: $TITLE"
  git -C "$HOME/notes" push -u
fi
