#!/bin/bash

unalias -a

if [[ $OSTYPE == *"darwin"* ]]; then
	alias l="ls --color"
	alias ll="ls -l --color"
	alias la="ls -alG --color"
else
	alias l="ls --color --group-directories-first"
	alias ll="ls -l --color --group-directories-first"
	alias la="ls -alG --color"
fi

alias vi="vim"
alias '?'=duckduckgo
alias gs="git status"
alias ga="git add"
alias gd="git diff"
alias gaa="git add -A"
alias gc="git commit"
alias gcb="git checkout -b"
alias gps="git push"
alias gpu="git pull"
alias gaf="ga  \$(git ls-files -m | fzf -m)"
alias gus="git restore --staged"
alias gusf="gus \$(git diff --name-only --cached | fzf -m)"
alias gdf="gd \$(git ls-files -m | fzf -m)"
alias gfu="gc --fixup \$(git log --oneline --color=never | fzf | awk '{ print \$1 }')"

# Tmux with UTF-8 support
alias tmux="tmux -u"

# Use nvim
alias vim="nvim"
