#!/bin/bash

# Setup GPG
GPG_TTY=$(tty)
SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
export GPG_TTY
export SSH_AUTH_SOCK

gpgconf --launch gpg-agent
gpg-connect-agent updatestartuptty /bye &>/dev/null

# Add Scripts
export PATH="$PATH:$HOME/.scripts"

source "$HOME/.aliases"

if [[ $OSTYPE == *'darwin'* ]]; then
  # Used by vimrc
  export PLATFORM='mac'
  export PATH="$PATH:/opt/homebrew/bin"

  # Enable Homebrew 
  eval "$(/opt/homebrew/bin/brew shellenv)"

  # Disable Homebrew telemetry
  export HOMEBREW_NO_ANALYTICS=1

  # Disable bash deprecation warning in macOS 
  export BASH_SILENCE_DEPRECATION_WARNING=1
fi

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

if command -v yarn &>/dev/null; then
  export PATH="$PATH:$(yarn global bin)"
fi
# Setup Prompt
source "$HOME/dotfiles/bash/prompt.sh"

# Add case-insensitive line completion
set completion-ignore-case on

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
[ -f /usr/share/bash-completion/completions/git ] && source /usr/share/bash-completion/completions/git
